### ISSUE TITLE
how to set the tensorflow using cpu only and the gup memory usage

### ISSUE THREAD

**Issue by lingbao00** [cyberfire/tensorflow-mtcnn#1]
i am doing face recognition,using your c++ implement,but i want to test the time of under cpu and gpu,tensorflow defaultly use gpu ,and all the memory,you use the c api,i am not know which function to set the two value,i hope you can help me.Thank you!

**Comment by cyberfire** [comment]
It is quite simple in python interface, by setting  tf.device
       
        with tf.device('/cpu:0'):

However, it is not easy in C API.

Tensorflow C API do provide interfaces for this purpose:

       TF_CAPI_EXPORT extern TF_SessionOptions* TF_NewSessionOptions();


       TF_CAPI_EXPORT extern void TF_SetConfig(TF_SessionOptions* options,
                                        const void* proto, size_t proto_len,
                                        TF_Status* status);
       //refers to: tensorflow/core/protobuf/config.proto

                                      
       TF_CAPI_EXPORT extern TF_Session* TF_NewSession(TF_Graph* graph,
                                                const TF_SessionOptions* opts,
                                                TF_Status* status);

However, the proto parameter in TF_SetConfig is a serialized protobuf, which is not a string as in python,  it will have to serialize the ConfigProto  first and load it later.

Hope above info can help you. 

Thanks,

Cyberfire

**Comment by BrownOfSummer** [comment]
I also encounter this problem. I get serialized protobuf in python tensorflow, then copy it to C API config, but this kind of tricky, and inconvenient. I think a C++ API may help a lot, could you help me figure out how to convert to C++ API?
