### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by billtiger** [cyberfire/tensorflow-mtcnn#2]
~/tensorflow-mtcnn-master/cpp/standalone$ sudo make test
the error is :
g++ test.o -o test  tensorflow_mtcnn.o comm_lib.o utils.o -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -Wl,-rpath,/usr/local/include/lib -L/usr/local/include/lib -ltensorflow
/usr/bin/ld: warning: libmklml_intel.so, needed by /usr/local/lib/libtensorflow.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libiomp5.so, needed by /usr/local/lib/libtensorflow.so, not found (try using -rpath or -rpath-link)
/usr/local/lib/libtensorflow.so：对‘dnnLRNCreateForward_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnConcatCreate_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnLRNCreateBackward_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnLayoutDelete_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnBatchNormalizationCreateBackward_v2_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘cblas_dgemm’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnPoolingCreateForward_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnLayoutDeserialize_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘cblas_cgemm’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnLayoutGetMemorySize_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnBatchNormalizationCreateForward_v2_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnExecute_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘omp_in_parallel@VERSION’未定义的引用
/usr/local/lib/libtensorflow.so：对‘cblas_zgemm’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnLayoutSerializationBufferSize_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnPoolingCreateBackward_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnConvolutionCreateBackwardBias_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnConvolutionCreateForward_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘cblas_sgemm’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnLayoutCompare_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnConvolutionCreateForwardBias_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnConversionExecute_F32’未定义的引用
//usr/local/lib/libtensorflow_framework.so：对‘i_calloc’未定义的引用
/usr/local/lib/libtensorflow.so：对‘omp_get_max_threads@VERSION’未定义的引用
/usr/local/lib/libtensorflow.so：对‘omp_get_thread_num@VERSION’未定义的引用
//usr/local/lib/libtensorflow_framework.so：对‘i_malloc’未定义的引用
/usr/local/lib/libtensorflow.so：对‘MKL_Domatcopy’未定义的引用
/usr/local/lib/libtensorflow.so：对‘GOMP_barrier@VERSION’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnConvolutionCreateBackwardFilter_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘omp_get_num_threads@VERSION’未定义的引用
//usr/local/lib/libtensorflow_framework.so：对‘i_free’未定义的引用
/usr/local/lib/libtensorflow.so：对‘MKL_Zomatcopy’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnDelete_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnLayoutCreate_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnLayoutSerialize_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnLayoutCreateFromPrimitive_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘MKL_Comatcopy’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnSumCreate_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘GOMP_parallel@VERSION’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnConversionCreate_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘MKL_Somatcopy’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnReLUCreateBackward_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnReLUCreateForward_F32’未定义的引用
/usr/local/lib/libtensorflow.so：对‘dnnConvolutionCreateBackwardData_F32’未定义的引用
//usr/local/lib/libtensorflow_framework.so：对‘i_realloc’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:45: recipe for target 'test' failed
make: *** [test] Error 1

how can i solve this problem?everybody give me recipe will thanks!!

**Comment by ghost** [comment]
看上去应该是链接库出问题了，libtensorflow.so可以从tensorflow的官网上获取，同时需要在Makefile里修改一下你的TR_ROOT，上面的错应该是程序没有链接到那个库。
