### ISSUE TITLE
how convert to mtcnn_frozen_model.pb?

### ISSUE THREAD

**Issue by billtiger** [cyberfire/tensorflow-mtcnn#4]
hello,first thank you contribute your codes!
now i have a problem,originally,there are three models. How do you convert to the mtcnn_frozen_model.pb?
 Is there have codes to convert?thanks!

**Comment by cyberfire** [comment]
Please see the save scripts in:
 https://github.com/cyberfire/tensorflow-mtcnn/tree/save_load

**Comment by billtiger** [comment]
ok. thank you very much !

**Comment by zkk0911** [comment]
Hi cyberfire / billtiger : There are some parameters I still don't understand.  what  are means of the parameters input_graph mean and input_checkpoint and how does the /models/save/graph.pb generate?    I just have three three separate checkpoints from pnet. rnet . onet
 @cyberfire @billtiger 
python freeze_graph.py --input_graph ./models/save/graph.pb --input_checkpoint ./models/save/mtcnn --output_graph=./models/save/freeze_model.pb $OUTPUT_NODE

**Comment by CHANGErIBE** [comment]
Hi zkk0911: I have gotten the same problem,there are three separated checkpoints from pnet.rnet and onet,Do you have solve this problem? @zkk0911 @billtiger @cyberfire

**Comment by kapildevkumar** [comment]
The original model from FaceNet has a graph file(.pb). If I load the model, there is a segmentation fault in C++. How to solve that?
@cyberfire
Graph File: 
https://drive.google.com/file/d/1EXPBSXwTaqrSC0OhUdXNmKSh9qJUQ55-/view
