### ISSUE TITLE
Face Alignment

### ISSUE THREAD

**Issue by ashokbugude** [cyberfire/tensorflow-mtcnn#9]
Can I please know how to align face after detection in c++ as done in https://github.com/davidsandberg/facenet/blob/master/src/align/align_dataset_mtcnn.py

**Comment by cyberfire** [comment]
@ashokbugude 

you can refer to this sample project:  https://github.com/OAID/FaceRecognition

Thanks,

**Comment by ashokbugude** [comment]
Thank you
